version: "3"

services:
  web-app: #link: acapo to-do-api
    build: ./my_todo
    ports:
      - "3000:3000"
    restart: on-failure
    container_name: web-app
  to-do-api:
    build: ./server_todo

    ports:
      - "5000:5000"
    restart: on-failure
    container_name: to-do-api
    volumes:
      - ./server_todo/uploads:/usr/src/app/uploads # Look at the server directory and copy everything into the app folder in the container
  #  environment:
